ladix:
    resource: "@LadixBundle/Resources/config/routing.xml"
    prefix:   /
ladix_createur:
    resource: "@LadixBundle/Resources/config/routing/createur.xml"
    prefix: /createur
ladix_projet:
    resource: "@LadixBundle/Resources/config/routing/projet.xml"
    prefix: /projet   
ladix_membre:
    resource: "@LadixBundle/Resources/config/routing/membre.xml"
    prefix: /membre  
ladix_structure:
    resource: "@LadixBundle/Resources/config/routing/structure.xml"
    prefix: /structure      
ladix_famille:
    resource: "@LadixBundle/Resources/config/routing/famille.xml"
    prefix: /famille
ladix_critere:
    resource: "@LadixBundle/Resources/config/routing/critere.xml"
    prefix: /critere  
ladix_reponse:
    resource: "@LadixBundle/Resources/config/routing/reponse.xml"
    prefix: /reponse   
ladix_question:
    resource: "@LadixBundle/Resources/config/routing/question.xml"
    prefix: /question 
ladix_groupe:
    resource: "@LadixBundle/Resources/config/routing/groupe.xml"
    prefix: /groupe     